# Generated by Django 3.1.5 on 2021-01-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('father_name', models.CharField(max_length=40)),
                ('mother_name', models.CharField(max_length=40)),
                ('student_id', models.IntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
